### ISSUE TITLE
Where to create OpenShift account?

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-cloud-openshift#17]
The guide should provide a link to where users can create an OpenShift account.  If credit card is necessary and there will be charges, these should be noted.

FYI, @gkwan-ibm.

**Comment by MaiHameed** [comment]
@yeekangc, thoughout the past couple of months, various changes have been made on Red Hat's side on their website. They have pulled out a plan just to reintroduce it a couple of weeks later. Due to the large variance on their site, I'm worried that specifying a plan or pointing to a specific webpage will quickly become outdated. The current site points to their OpenShift plans page, and there is currently a trial/free version so I never mentioned the possibility of payment. If you would still like changes to be made let me know, otherwise those are my justifications for the decisions around that.

**Comment by yeekangc** [comment]
We should take the guesswork away from the users.  Pointing to a top-level page is fine.  There should at least be an indication of what users should consider if they are starting out or doing it for the first time too.
